export const COURSES = [
  {
    id: 1,
    name: 'Advanced Web Architecture',
    instructor: 'Dr. Michael Chen',
    code: 'CS402',
    progress: 85,
    modules: 15,
    credits: 4,
  },
  {
    id: 2,
    name: 'Artificial Intelligence & ML',
    instructor: 'Dr. Sarah Johnson',
    code: 'AI301',
    progress: 45,
    modules: 20,
    credits: 5,
  },
  {
    id: 3,
    name: 'Cybersecurity Fundamentals',
    instructor: 'Prof. Alan Turing',
    code: 'SEC101',
    progress: 100,
    modules: 10,
    credits: 3,
  },
  {
    id: 4,
    name: 'Mobile App Development',
    instructor: 'Prof. Steve Jobs',
    code: 'MOB202',
    progress: 25,
    modules: 18,
    credits: 4,
  },
  {
    id: 5,
    name: 'Database Management Systems',
    instructor: 'Prof. Grace Hopper',
    code: 'DB404',
    progress: 60,
    modules: 14,
    credits: 4,
  },
];
