export const INTERNSHIPS = [
  {
    id: 1,
    title: 'Software Development Intern',
    company: 'Google',
    location: 'Bangalore, India',
    stipend: '₹50,000 / month',
    type: 'Remote',
    duration: '3 Months',
    logo: 'https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png',
  },
  {
    id: 2,
    title: 'Frontend Developer',
    company: 'Microsoft',
    location: 'Hyderabad, India',
    stipend: '₹45,000 / month',
    type: 'Hybrid',
    duration: '6 Months',
    logo: 'https://cdn.iconscout.com/icon/free/png-256/free-microsoft-brand-logo-symbol-computing-windows-advertising-2-1175024.png',
  },
  {
    id: 3,
    title: 'Data Analyst Intern',
    company: 'Amazon',
    location: 'Seattle, WA',
    stipend: '$4,000 / month',
    type: 'On-site',
    duration: '4 Months',
    logo: 'https://cdn.iconscout.com/icon/free/png-256/free-amazon-brand-logo-symbol-computing-company-advertising-2-1175029.png',
  },
  {
    id: 4,
    title: 'Product Design Intern',
    company: 'Adobe',
    location: 'Noida, India',
    stipend: '₹35,000 / month',
    type: 'On-site',
    duration: '6 Months',
    logo: 'https://cdn.iconscout.com/icon/free/png-256/free-adobe-logo-icon-download-in-svg-png-gif-formats--brand-brands-pack-social-media-icons-226462.png',
  },
  {
    id: 5,
    title: 'Cybersecurity Analyst',
    company: 'Cisco',
    location: 'Pune, India',
    stipend: '₹30,000 / month',
    type: 'Remote',
    duration: '3 Months',
    logo: 'https://cdn.iconscout.com/icon/free/png-256/free-cisco-brand-logo-symbol-computing-company-advertising-1175034.png',
  },
  {
    id: 6,
    title: 'Mobile App Developer',
    company: 'Zomato',
    location: 'Gurugram, India',
    stipend: '₹25,000 / month',
    type: 'In-office',
    duration: '6 Months',
    logo: 'https://cdn.iconscout.com/icon/free/png-256/free-zomato-logo-icon-download-in-svg-png-gif-formats--brand-brands-pack-social-media-icons-226490.png',
  },
];
